### ISSUE TITLE
Quotes are only changed when running "backticks" from [CTRL] + [SHIFT] + P

### ISSUE THREAD

**Issue by snugam** [Mossop/vscode-backticks#39]
When calling Backticks from CTRL SHIFT P it works fine, but not with the keyboard shortcut, even though it is defined correctly as a keyboard shortcut (there are no other conflicting shortcuts).

When enabling _[Developer: Toggle Keyboard Shortcuts Troubleshooting]_ here is what is shown

`[2022-06-10 13:04:34.923] [renderer1] [error] [Extension Host] Error: command 'backticks.test.complete' not found
    at v._tryExecuteCommand (vscode-file://vscode-app/c:/Users/magnu/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1706:3532)
    at v.executeCommand (vscode-file://vscode-app/c:/Users/magnu/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1706:3414)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

Visual Studio Code Version:  1.68.0

**Comment by snugam** [comment]
it is working, thank you!
